/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clericyi_player_MainActivity */

#ifndef _Included_com_clericyi_player_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_clericyi_player_MainActivity
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_clericyi_player_MainActivity_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
